import type { RegulatoryNoticeSource } from './types';

export const REFERENCE_NOTICES: RegulatoryNoticeSource[] = [
  {
    noticeNumber: 'Periodic report no.(1) For 2026',
    title: 'Recall of Diclac Ampoule 75 mg',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Diclac Ampoule 75 mg',
    manufacturer: 'MUP / Hexal',
    batchNumbers: ['260101', '260102'],
    registrationNumber: 'EDA-EG-2021-00124',
    reason: 'Non-compliance with particulate matter specifications',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/azipl1v1/diclac-amp-75mg-%D8%B3%D8%AD%D8%A8.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/01',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(2) For 2026',
    title: 'Alert on Diclac 75mg Ampoule',
    year: 2026,
    noticeType: 'ALERT',
    recallClass: null,
    productName: 'Diclac 75mg Ampoule',
    manufacturer: 'Hexal AG',
    batchNumbers: ['260103'],
    registrationNumber: 'EDA-EG-2021-00124',
    reason: 'Suspected counterfeit batch in local distribution',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/1xjp2aae/diclac-75mg-amp-alert.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/02',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(3) For 2026',
    title: 'Recall of Megafen N 100mg/5ml',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Megafen N 100mg/5ml suspension',
    manufacturer: 'Alexandria Pharmaceuticals',
    batchNumbers: ['MG2601'],
    registrationNumber: 'EDA-EG-2019-09412',
    reason: 'Dissolution rate deviation during stability testing',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/5q5d5uuy/megafen-n-susp-100mg-5ml-%D8%B3%D8%AD%D8%A8.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/03',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(4) For 2026',
    title: 'Alert Notice on VARNOVA 10mg Film Coated Tablets',
    year: 2026,
    noticeType: 'ALERT',
    recallClass: null,
    productName: 'VARNOVA 10mg Film Coated Tablets',
    manufacturer: 'Eva Pharma',
    batchNumbers: ['VN2604'],
    registrationNumber: 'EDA-EG-2020-04192',
    reason: 'Packaging anomaly observed in outer secondary packaging',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/omxpxo3n/varnova-10mg-film-coated-tablets-alert.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/04',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(5) For 2026',
    title: 'Recall of Neo-polyderm Cream',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_III',
    productName: 'Neo-polyderm cream',
    manufacturer: 'Amoun Pharmaceutical Co.',
    batchNumbers: ['NP2605'],
    registrationNumber: 'EDA-EG-2018-03120',
    reason: 'Minor labeling text error on outer carton',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/1xip5w5e/neo-polyderm-cream-%D8%B3%D8%AD%D8%A8.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/05',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(6) For 2026',
    title: 'Alert Notice on Omnipaque 350 mg/ml',
    year: 2026,
    noticeType: 'ALERT',
    recallClass: null,
    productName: 'Omnipaque 350 mg/ml',
    manufacturer: 'GE Healthcare',
    batchNumbers: ['OM2606'],
    registrationNumber: 'EDA-EG-2022-01993',
    reason: 'Precautionary quarantine for inspection of seal integrity',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/h5epvkhw/omnipaque-350-mg-ml.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/06',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(7) For 2026',
    title: 'Recall of Zinnat 500mg Film Coated Tablets',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Zinnat 500mg Film coated Tablets',
    manufacturer: 'GlaxoSmithKline (GSK)',
    batchNumbers: ['ZN2607A', 'ZN2607B'],
    registrationNumber: 'EDA-EG-2017-08819',
    reason: 'Assay out of specification during ongoing stability studies',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/4e1j4q2l/zinnat-500mg-film-coated-tablets.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/07',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(8) For 2026',
    title: 'Recall of Neo chem 30%',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Neo chem 30%',
    manufacturer: 'Chemical Industries Development (CID)',
    batchNumbers: ['NC2608'],
    registrationNumber: 'EDA-EG-2016-01284',
    reason: 'pH deviation in finished product testing',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/4c0p3e2o/neo-chem-30.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/08',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(9) For 2026',
    title: 'Commercial Fraud Alert on Fortum 1g Powder for Injection',
    year: 2026,
    noticeType: 'COMMERCIAL_FRAUD',
    recallClass: 'CLASS_I',
    productName: 'Fortum 1g powder for injection/infusion',
    manufacturer: 'GlaxoSmithKline Egypt',
    batchNumbers: ['FT2609'],
    registrationNumber: 'EDA-EG-2015-00412',
    reason: 'Falsified batch circulating without active pharmaceutical ingredient',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/tzdftkno/fortum-1g.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/09',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(10) For 2026',
    title: 'Recall of Colchicine 0.5mg Tablets',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_III',
    productName: 'Colchicine 0.5mg Tablets',
    manufacturer: 'El Nasr Pharmaceutical Chemicals (ADWIA)',
    batchNumbers: ['COL2610'],
    registrationNumber: 'EDA-EG-2019-05514',
    reason: 'Labeling artwork mismatch on leaflet',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/3y1b4mqa/colchicine-0-5mg-tablets.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/10',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(11) For 2026',
    title: 'Alert Notice on Alphintern Tablets',
    year: 2026,
    noticeType: 'ALERT',
    recallClass: null,
    productName: 'Alphintern Gastro-Resistant Tablets',
    manufacturer: 'Amoun Pharmaceutical Co.',
    batchNumbers: ['AL2611'],
    registrationNumber: 'EDA-EG-2018-09123',
    reason: 'Suspected parallel import without EDA serialization barcode',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/g31p30a4/alphintern.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/11',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(15) For 2026',
    title: 'Recall of E-moxclav 1gm Tablets',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'E-moxclav 1gm Tablets',
    manufacturer: 'EIPICO',
    batchNumbers: ['EM2615A', 'EM2615B'],
    registrationNumber: 'EDA-EG-2020-07743',
    reason: 'Degradation product exceeding limits under accelerated stability',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/l41bt11e/e-moxclav-1gm.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/15',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(16) For 2026',
    title: 'Recall of Adport 1mg Hard Gelatin Capsules',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Adport 1mg Hard Gelatin Capsules',
    manufacturer: 'Sandoz Egypt',
    batchNumbers: ['AD2616'],
    registrationNumber: 'EDA-EG-2022-03190',
    reason: 'Disintegration time failure in stability samples',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/m30p5k2w/adport-1mg.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/16',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(20) For 2026',
    title: 'Alert Notice on Cialis 20mg Film Coated Tablets',
    year: 2026,
    noticeType: 'ALERT',
    recallClass: null,
    productName: 'Cialis 20mg Film Coated Tablets',
    manufacturer: 'Eli Lilly',
    batchNumbers: ['CL2620'],
    registrationNumber: 'EDA-EG-2016-04412',
    reason: 'Unregistered parallel packaging detected in private pharmacies',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/2wdicvk2/1930-cialis-20mg.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/20',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(39) For 2026',
    title: 'Recall of Flumox 1000mg Film Coated Tablets',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Flumox 1000mg film coated tablet',
    manufacturer: 'EIPICO',
    batchNumbers: ['FX2639'],
    registrationNumber: 'EDA-EG-2018-06654',
    reason: 'Dissolution specification failure at 45 minutes',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/vy0a23pc/flumox1000mg.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/39',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(41) For 2026',
    title: 'Recall of Microserc 8mg Tablets',
    year: 2026,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Microserc 8mg Tablets',
    manufacturer: 'Global Napi Pharmaceuticals',
    batchNumbers: ['MS2641'],
    registrationNumber: 'EDA-EG-2017-02381',
    reason: 'Impurities profile out of specification',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/qlpjj1mk/microserc-8-mg-%D8%B3%D8%AD%D8%A8-1980-1.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/41',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(49) For 2026',
    title: 'Alert Notice on Zurcal IV Powder for Solution',
    year: 2026,
    noticeType: 'ALERT',
    recallClass: null,
    productName: 'Zurcal powder for solution for IV injection 40mg',
    manufacturer: 'Takeda Pharma / AUG Pharma',
    batchNumbers: ['ZC2649'],
    registrationNumber: 'EDA-EG-2021-08119',
    reason: 'Reconstitution visual clarity alert',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/nmwnwchs/zurcal-iv-%D8%BA%D8%B4-2020.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/49',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(72) For 2026',
    title: 'Commercial Fraud Alert on Ciprofar 750mg Tablets',
    year: 2026,
    noticeType: 'COMMERCIAL_FRAUD',
    recallClass: 'CLASS_I',
    productName: 'Ciprofar 750mg Tablets',
    manufacturer: 'Pharco Pharmaceuticals',
    batchNumbers: ['CP2672'],
    registrationNumber: 'EDA-EG-2016-01934',
    reason: 'Counterfeit packaging and substandard dissolution identified',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/lt2e5fzl/%D8%BA%D8%B4-%D8%AA%D8%AC%D8%A7%D8%B1%D9%8A-2127-ciprofar.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2026/72',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(1) For 2025',
    title: 'Recall of Amoxicillin 500mg Capsules',
    year: 2025,
    noticeType: 'RECALL',
    recallClass: 'CLASS_II',
    productName: 'Amoxicillin 500mg Capsules',
    manufacturer: 'Medical Union Pharmaceuticals (MUP)',
    batchNumbers: ['AM2501'],
    registrationNumber: 'EDA-EG-2015-09823',
    reason: 'Potency decrease observed during year 2 stability review',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/p3ep321/amox-500-2025-01.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2025/01',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(12) For 2025',
    title: 'Recall of Paracetamol 500mg Tablets',
    year: 2025,
    noticeType: 'RECALL',
    recallClass: 'CLASS_III',
    productName: 'Paracetamol 500mg Tablets',
    manufacturer: 'Misr Co. for Pharmaceuticals',
    batchNumbers: ['PC2512'],
    registrationNumber: 'EDA-EG-2014-00192',
    reason: 'Minor printing variation on blister foil',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/8931bna/para-500-2025-12.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2025/12',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
  {
    noticeNumber: 'Periodic report no.(45) For 2025',
    title: 'Alert on Omeprazole 20mg Delayed-Release Capsules',
    year: 2025,
    noticeType: 'ALERT',
    recallClass: null,
    productName: 'Omeprazole 20mg Delayed-Release Capsules',
    manufacturer: 'Sedico Pharmaceuticals',
    batchNumbers: ['OM2545'],
    registrationNumber: 'EDA-EG-2019-01129',
    reason: 'Storage temperature excursion notice during transit',
    sourceUrl: 'https://www.edaegypt.gov.eg/media/7u12vba/omep-20-2025-45.pdf',
    sourceAuthority: 'Egyptian Drug Authority',
    sourceDocCode: 'EDA/VIG/2025/45',
    sourceVersion: '1.0',
    retrievedAt: '2026-08-15T00:00:00.000Z',
  },
];
