import type { ImportKind } from './types';

/**
 * Deterministic aliases for canonical fields.
 * Stored in normalized snake_case / words form.
 */
export const CANONICAL_FIELD_ALIASES: Record<ImportKind, Record<string, readonly string[]>> = {
  ORDERS: {
    order_id: [
      'order_id',
      'order_number',
      'order_no',
      'order_num',
      'po_number',
      'po_no',
      'purchase_order_id',
      'purchase_order_number',
      'purchase_order_no',
      'order_ref',
      'order_reference',
      'order_code',
      'transaction_id',
      'order_key',
    ],
    pharmacy_id: [
      'pharmacy_id',
      'pharmacy_code',
      'pharmacy_num',
      'store_id',
      'store_code',
      'store_number',
      'branch_id',
      'branch_code',
      'customer_id',
      'customer_code',
      'client_id',
      'client_code',
      'buyer_id',
      'buyer_code',
      'account_id',
      'account_number',
    ],
    pharmacy_name: [
      'pharmacy_name',
      'pharmacy',
      'store_name',
      'branch_name',
      'customer_name',
      'client_name',
      'buyer_name',
      'account_name',
    ],
    placed_at: [
      'placed_at',
      'order_date',
      'order_time',
      'order_datetime',
      'order_timestamp',
      'created_at',
      'created_date',
      'creation_time',
      'placed_date',
      'placed_time',
      'placed_timestamp',
      'order_placed_at',
      'date_ordered',
      'order_placed',
    ],
    product_id: [
      'product_id',
      'product_code',
      'sku',
      'sku_id',
      'sku_code',
      'item_code',
      'item_id',
      'item_number',
      'medicine_code',
      'medicine_id',
      'drug_code',
      'drug_id',
      'material_id',
      'material_code',
      'gtin',
      'barcode',
    ],
    product_name: [
      'product_name',
      'product',
      'item_name',
      'item_description',
      'item_title',
      'medicine_name',
      'drug_name',
      'product_title',
      'product_description',
      'description',
      'name',
    ],
    manufacturer: [
      'manufacturer',
      'manufacturer_name',
      'mfg',
      'producer',
      'brand',
      'company',
      'pharma_company',
      'lab',
      'laboratory',
    ],
    requested_qty: [
      'requested_qty',
      'requested_quantity',
      'qty_requested',
      'qty_ordered',
      'quantity_ordered',
      'order_qty',
      'ordered_qty',
      'req_qty',
      'units_ordered',
      'requested_units',
      'target_qty',
    ],
    unit: [
      'unit',
      'unit_of_measure',
      'uom',
      'pack_unit',
      'packaging',
      'package_type',
      'dosage_form',
      'form',
    ],
  },

  OFFERS: {
    offer_id: [
      'offer_id',
      'offer_number',
      'offer_no',
      'quote_id',
      'quote_number',
      'quote_no',
      'quotation_id',
      'bid_id',
      'bid_number',
      'proposal_id',
      'offer_code',
      'quote_code',
    ],
    order_id: [
      'order_id',
      'order_number',
      'order_no',
      'po_number',
      'po_no',
      'order_ref',
      'order_reference',
      'order_code',
    ],
    supplier_id: [
      'supplier_id',
      'supplier_code',
      'vendor_id',
      'vendor_code',
      'vendor_num',
      'vendor_number',
      'wholesaler_id',
      'wholesaler_code',
      'distributor_id',
      'distributor_code',
      'seller_id',
      'seller_code',
    ],
    supplier_name: [
      'supplier_name',
      'supplier',
      'vendor_name',
      'vendor',
      'wholesaler_name',
      'wholesaler',
      'distributor_name',
      'distributor',
      'seller_name',
      'seller',
    ],
    product_id: [
      'product_id',
      'product_code',
      'sku',
      'sku_id',
      'sku_code',
      'item_code',
      'item_id',
      'medicine_code',
      'medicine_id',
      'gtin',
    ],
    available_qty: [
      'available_qty',
      'available_quantity',
      'qty_available',
      'stock_qty',
      'stock_quantity',
      'offered_qty',
      'offered_quantity',
      'supply_qty',
      'avail_qty',
      'units_available',
    ],
    unit_price_egp: [
      'unit_price_egp',
      'unit_price',
      'price_egp',
      'unit_cost',
      'cost_egp',
      'quoted_price',
      'cost_per_unit',
      'price_per_unit',
      'rate',
      'unit_rate',
      'price',
    ],
    discount_percent: [
      'discount_percent',
      'discount_pct',
      'discount',
      'discount_percentage',
      'discount_rate',
      'discount_value',
      'rebate_percent',
      'rebate_pct',
      'disc_pct',
    ],
    promised_delivery_at: [
      'promised_delivery_at',
      'promised_delivery',
      'promised_at',
      'expected_delivery_at',
      'expected_delivery',
      'delivery_promise',
      'promised_date',
      'promised_time',
      'eta',
      'est_delivery',
      'estimated_delivery',
    ],
    offered_at: [
      'offered_at',
      'offer_date',
      'offer_time',
      'offer_timestamp',
      'quote_date',
      'quote_time',
      'quote_timestamp',
      'quoted_at',
      'bid_date',
      'bid_time',
      'created_at',
      'offered_date',
    ],
  },

  OUTCOMES: {
    order_id: [
      'order_id',
      'order_number',
      'order_no',
      'po_number',
      'po_no',
      'order_ref',
      'order_reference',
    ],
    supplier_id: [
      'supplier_id',
      'supplier_code',
      'vendor_id',
      'vendor_code',
      'wholesaler_id',
      'distributor_id',
      'seller_id',
      'fulfilled_by_id',
    ],
    product_id: [
      'product_id',
      'product_code',
      'sku',
      'sku_id',
      'item_code',
      'item_id',
      'medicine_code',
    ],
    filled_qty: [
      'filled_qty',
      'fulfilled_qty',
      'qty_filled',
      'qty_fulfilled',
      'delivered_qty',
      'qty_delivered',
      'received_qty',
      'actual_qty',
      'delivered_units',
      'filled_units',
    ],
    delivered_at: [
      'delivered_at',
      'delivery_time',
      'delivery_date',
      'delivery_timestamp',
      'delivered_date',
      'delivered_time',
      'received_at',
      'received_date',
      'fulfilled_at',
      'arrival_time',
    ],
    cancelled: [
      'cancelled',
      'is_cancelled',
      'canceled',
      'is_canceled',
      'voided',
      'is_void',
      'status_cancelled',
      'order_cancelled',
    ],
    cancellation_reason: [
      'cancellation_reason',
      'cancel_reason',
      'reason_for_cancellation',
      'cancellation_note',
      'cancel_note',
      'reason_cancelled',
    ],
    outcome_final: [
      'outcome_final',
      'is_final',
      'final_outcome',
      'is_completed',
      'closed',
      'final',
      'is_closed',
    ],
  },

  DECISIONS: {
    decision_id: [
      'decision_id',
      'decision_number',
      'decision_no',
      'selection_id',
      'resolution_id',
      'decision_code',
      'decision_ref',
    ],
    order_id: [
      'order_id',
      'order_number',
      'order_no',
      'po_number',
      'po_no',
      'order_ref',
      'order_reference',
    ],
    selected_supplier_id: [
      'selected_supplier_id',
      'selected_supplier',
      'chosen_supplier_id',
      'chosen_supplier',
      'winner_supplier_id',
      'winning_supplier_id',
      'selected_vendor_id',
      'selected_vendor',
      'supplier_id',
    ],
    decided_at: [
      'decided_at',
      'decision_time',
      'decision_date',
      'decision_timestamp',
      'selected_at',
      'selection_time',
      'selection_date',
      'decided_date',
      'timestamp',
      'created_at',
    ],
    agent_name: [
      'agent_name',
      'model_name',
      'decision_agent',
      'agent',
      'algorithm_name',
      'system_name',
      'ai_agent',
    ],
    agent_version: [
      'agent_version',
      'model_version',
      'system_version',
      'version',
      'agent_ver',
      'algorithm_version',
    ],
    confidence: [
      'confidence',
      'confidence_score',
      'model_confidence',
      'score',
      'prob',
      'probability',
    ],
    selection_reason: [
      'selection_reason',
      'rationale',
      'reason',
      'decision_rationale',
      'decision_reason',
      'selection_rationale',
      'notes',
      'explanation',
    ],
  },
};
