/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RegulatoryRouteImport } from './routes/regulatory'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as DecisionsDecisionIdRouteImport } from './routes/decisions.$decisionId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryRoute = RegulatoryRouteImport.update({
  id: '/regulatory',
  path: '/regulatory',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsDecisionIdRoute = DecisionsDecisionIdRouteImport.update({
  id: '/decisions/$decisionId',
  path: '/decisions/$decisionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/$supplierId',
  path: '/$supplierId',
  getParentRoute: () => SuppliersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/regulatory': typeof RegulatoryRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/traceability': typeof TraceabilityRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/regulatory': typeof RegulatoryRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/traceability': typeof TraceabilityRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/regulatory': typeof RegulatoryRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/traceability': typeof TraceabilityRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imports'
    | '/orders'
    | '/regulatory'
    | '/suppliers'
    | '/traceability'
    | '/decisions/$decisionId'
    | '/orders/$orderId'
    | '/suppliers/$supplierId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imports'
    | '/orders'
    | '/regulatory'
    | '/suppliers'
    | '/traceability'
    | '/decisions/$decisionId'
    | '/orders/$orderId'
    | '/suppliers/$supplierId'
  id:
    | '__root__'
    | '/'
    | '/imports'
    | '/orders'
    | '/regulatory'
    | '/suppliers'
    | '/traceability'
    | '/decisions/$decisionId'
    | '/orders/$orderId'
    | '/suppliers/$supplierId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportsRoute: typeof ImportsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  RegulatoryRoute: typeof RegulatoryRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
  TraceabilityRoute: typeof TraceabilityRoute
  DecisionsDecisionIdRoute: typeof DecisionsDecisionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory': {
      id: '/regulatory'
      path: '/regulatory'
      fullPath: '/regulatory'
      preLoaderRoute: typeof RegulatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$decisionId': {
      id: '/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof DecisionsDecisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface SuppliersRouteChildren {
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportsRoute: ImportsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  RegulatoryRoute: RegulatoryRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
  TraceabilityRoute: TraceabilityRoute,
  DecisionsDecisionIdRoute: DecisionsDecisionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
